package yunzhixun

const (
	YUNZHIXUN_API_HOST = "https://open.ucpaas.com"
)

type YUNZHIXUN_API_TYPE int

const (
	SMS_SEND_SINGLE YUNZHIXUN_API_TYPE = iota
	SMS_SEND_GROUP
	SMS_SEND_STATUS
	SMS_TEMPLATE_ADD
	SMS_TEMPLATE_QUERY
	SMS_TEMPLATE_EDIT
	SMS_TEMPLATE_DELETE
)

const (
	YUNZHIXUN_RESULT_CODE_UNSUPPORTED_RESP      = -2
	YUNZHIXUN_RESULT_CODE_NETWORK_ERROR         = -1
	YUNZHIXUN_RESULT_TESTMODE_UNSUPPORTED_ERROR = -3

	YUNZHIXUN_RESULT_CODE_OK = 0
)
